// Complete Kanji data from kanjidamage.com
// Total: 1634 entries
// Source: https://www.kanjidamage.com/kanji

const kanjiData = [
  { kanji: '一', meaning: 'one (line radical)' },
  { kanji: '二', meaning: 'two' },
  { kanji: '三', meaning: 'three' },
  { kanji: '了', meaning: 'total' },
  { kanji: '子', meaning: 'child' },
  { kanji: '女', meaning: 'woman' },
  { kanji: '好', meaning: 'like' },
  { kanji: '姦', meaning: 'rape' },
  { kanji: '口', meaning: 'mouth (small box radical)' },
  { kanji: '品', meaning: 'products' },
  { kanji: '言', meaning: 'say' },
  { kanji: '下', meaning: 'below' },
  { kanji: '不', meaning: 'un' },
  { kanji: '否', meaning: 'no' },
  { kanji: '十', meaning: 'ten' },
  { kanji: '古', meaning: 'old' },
  { kanji: '叶', meaning: 'dream come true' },
  { kanji: '計', meaning: 'measure' },
  { kanji: '七', meaning: 'seven' },
  { kanji: '比', meaning: 'compare' },
  { kanji: '叱', meaning: 'scold' },
  { kanji: '日', meaning: 'sun, day' },
  { kanji: '旨', meaning: 'the gist' },
  { kanji: '昆', meaning: 'insect' },
  { kanji: '唱', meaning: 'chant' },
  { kanji: '晶', meaning: 'crystal' },
  { kanji: '旧', meaning: 'former' },
  { kanji: '早', meaning: 'early' },
  { kanji: '旦', meaning: 'danna (husband)' },
  { kanji: '白', meaning: 'white' },
  { kanji: '皆', meaning: 'everyone' },
  { kanji: '水', meaning: 'water' },
  { kanji: '泉', meaning: 'spring' },
  { kanji: '氷', meaning: 'ice' },
  { kanji: '永', meaning: 'forever' },
  { kanji: '泳', meaning: 'swim' },
  { kanji: '泊', meaning: 'stay for the night' },
  { kanji: '汁', meaning: 'juice, soup' },
  { kanji: '混', meaning: 'mix' },
  { kanji: '月', meaning: 'moon (organ)' },
  { kanji: '湖', meaning: 'big lake' },
  { kanji: '明', meaning: 'bright' },
  { kanji: '脂', meaning: 'animal fat' },
  { kanji: '胆', meaning: 'gall bladder / daring' },
  { kanji: '朝', meaning: 'morning' },
  { kanji: '火', meaning: 'fire' },
  { kanji: '炎', meaning: 'flame' },
  { kanji: '淡', meaning: 'faint' },
  { kanji: '談', meaning: 'consult' },
  { kanji: '丁', meaning: 'nail' },
  { kanji: '灯', meaning: 'streetlight' },
  { kanji: '可', meaning: 'possible' },
  { kanji: '河', meaning: 'stream' },
  { kanji: '訂', meaning: 'revise' },
  { kanji: '田', meaning: 'rice field' },
  { kanji: '町', meaning: 'neighborhood, small town' },
  { kanji: '畑', meaning: 'cultivated field' },
  { kanji: '胃', meaning: 'stomach' },
  { kanji: '入', meaning: 'put/go in' },
  { kanji: '人', meaning: 'person' },
  { kanji: '何', meaning: 'what?!?' },
  { kanji: '信', meaning: 'believe' },
  { kanji: '化', meaning: 'transform' },
  { kanji: '花', meaning: 'flower' },
  { kanji: '苦', meaning: 'suffer' },
  { kanji: '草', meaning: 'grass' },
  { kanji: '荷', meaning: 'luggage' },
  { kanji: '内', meaning: 'the inside' },
  { kanji: '肉', meaning: 'meat' },
  { kanji: '円', meaning: 'yen/circle' },
  { kanji: '市', meaning: 'small city (dagger　radical)' },
  { kanji: '肺', meaning: 'lung' },
  { kanji: '姉', meaning: 'older sister' },
  { kanji: '目', meaning: 'eye' },
  { kanji: '冒', meaning: 'dare' },
  { kanji: '帽', meaning: 'hat' },
  { kanji: '自', meaning: 'my own' },
  { kanji: '亭', meaning: 'restaurant' },
  { kanji: '停', meaning: 'bring to a halt' },
  { kanji: '卒', meaning: 'graduate' },
  { kanji: '方', meaning: 'direction / method / person' },
  { kanji: '万', meaning: '10000' },
  { kanji: '訪', meaning: 'formal visit' },
  { kanji: '妨', meaning: 'prevent' },
  { kanji: '肪', meaning: 'fatty food' },
  { kanji: '又', meaning: 'again (crotch radical)' },
  { kanji: '双', meaning: 'pair' },
  { kanji: '奴', meaning: 'servant / dood' },
  { kanji: '文', meaning: 'culture/ sentence' },
  { kanji: '斉', meaning: 'unison' },
  { kanji: '済', meaning: 'economy / to be over' },
  { kanji: '収', meaning: 'get' },
  { kanji: '叫', meaning: 'shout' },
  { kanji: '心', meaning: 'heart' },
  { kanji: '必', meaning: 'surely' },
  { kanji: '怒', meaning: 'get mad' },
  { kanji: '息', meaning: 'son / breath' },
  { kanji: '思', meaning: 'think' },
  { kanji: '亡', meaning: 'dying' },
  { kanji: '忙', meaning: 'busy' },
  { kanji: '忘', meaning: 'forget' },
  { kanji: '盲', meaning: 'blind, ignorant' },
  { kanji: '妄', meaning: 'without reason or permission' },
  { kanji: '慢', meaning: 'neglect/ egotistic' },
  { kanji: '漫', meaning: 'manga' },
  { kanji: '亜', meaning: 'sub-' },
  { kanji: '悪', meaning: 'bad' },
  { kanji: '夕', meaning: 'evening' },
  { kanji: '多', meaning: 'many' },
  { kanji: '夢', meaning: 'dream' },
  { kanji: '夜', meaning: 'late night' },
  { kanji: '液', meaning: 'liquid' },
  { kanji: '名', meaning: 'name, famous' },
  { kanji: '死', meaning: 'death' },
  { kanji: '外', meaning: 'outside' },
  { kanji: '上', meaning: 'above' },
  { kanji: '卓', meaning: 'dinner table' },
  { kanji: '占', meaning: 'fortune teller/ occupy' },
  { kanji: '点', meaning: 'point' },
  { kanji: '宅', meaning: 'residence' },
  { kanji: '安', meaning: 'cheap / safe' },
  { kanji: '字', meaning: 'letter' },
  { kanji: '宣', meaning: 'announce' },
  { kanji: '喧', meaning: 'fight or quarrel' },
  { kanji: '八', meaning: 'eight' },
  { kanji: '穴', meaning: 'hole' },
  { kanji: '六', meaning: 'six' },
  { kanji: '沿', meaning: 'run parallel to' },
  { kanji: 'ム', meaning: 'moocow' },
  { kanji: '公', meaning: 'public' },
  { kanji: '訟', meaning: 'lawsuit' },
  { kanji: '台', meaning: 'big thing counter' },
  { kanji: '治', meaning: 'cure' },
  { kanji: '始', meaning: 'begin' },
  { kanji: '怠', meaning: 'lazy' },
  { kanji: '能', meaning: 'talent' },
  { kanji: '熊', meaning: 'bear' },
  { kanji: '態', meaning: 'looks like' },
  { kanji: '仏', meaning: 'Buddha' },
  { kanji: '立', meaning: 'stand up' },
  { kanji: '辛', meaning: 'spicy / painful' },
  { kanji: '幸', meaning: 'luck, happiness' },
  { kanji: '宰', meaning: 'manager' },
  { kanji: '泣', meaning: 'cry' },
  { kanji: '位', meaning: 'rank' },
  { kanji: '音', meaning: 'sound' },
  { kanji: '章', meaning: 'emblem / chapter' },
  { kanji: '暗', meaning: 'dark' },
  { kanji: '意', meaning: 'meaning' },
  { kanji: '億', meaning: 'a hundred million' },
  { kanji: '憶', meaning: 'recollect' },
  { kanji: '門', meaning: 'gate' },
  { kanji: '闇', meaning: 'pitch-black darkness' },
  { kanji: '間', meaning: 'a period of time' },
  { kanji: '問', meaning: 'question, problem' },
  { kanji: '刀', meaning: 'sword' },
  { kanji: '前', meaning: 'before' },
  { kanji: '切', meaning: 'cut / important' },
  { kanji: '召', meaning: 'summon' },
  { kanji: '昭', meaning: 'shining / Showa era' },
  { kanji: '照', meaning: 'contrast' },
  { kanji: '分', meaning: 'understand / divide / minute' },
  { kanji: '剤', meaning: 'type of medicine' },
  { kanji: '罰', meaning: 'punishment' },
  { kanji: '刃', meaning: 'blade' },
  { kanji: '忍', meaning: 'hide / endure' },
  { kanji: '認', meaning: 'admit' },
  { kanji: '力', meaning: 'strong' },
  { kanji: '加', meaning: 'add' },
  { kanji: '協', meaning: 'cooperate' },
  { kanji: '脅', meaning: 'threaten' },
  { kanji: '努', meaning: 'make an effort' },
  { kanji: '男', meaning: 'man' },
  { kanji: '九', meaning: 'the number 9' },
  { kanji: '究', meaning: 'research' },
  { kanji: '丸', meaning: 'round' },
  { kanji: '熟', meaning: 'get good at' },
  { kanji: '執', meaning: 'to hella do' },
  { kanji: '小', meaning: 'small size' },
  { kanji: '少', meaning: 'a little (amount)' },
  { kanji: '劣', meaning: 'inferiority' },
  { kanji: '妙', meaning: 'odd' },
  { kanji: '省', meaning: 'ministry / cut down on' },
  { kanji: '京', meaning: 'capital' },
  { kanji: '涼', meaning: 'cool place' },
  { kanji: '景', meaning: 'scene' },
  { kanji: '示', meaning: 'show (altar radical)' },
  { kanji: '宗', meaning: 'religion' },
  { kanji: '寂', meaning: 'lonely' },
  { kanji: '督', meaning: 'supervisor' },
  { kanji: '幼', meaning: 'childhood' },
  { kanji: '玄', meaning: 'deep profound' },
  { kanji: '畜', meaning: 'raising of domestic animals' },
  { kanji: '蓄', meaning: 'store or put aside' },
  { kanji: '糸', meaning: 'string' },
  { kanji: '紹', meaning: 'acquaint' },
  { kanji: '線', meaning: 'line' },
  { kanji: '綿', meaning: 'cotton' },
  { kanji: '細', meaning: 'slender' },
  { kanji: '総', meaning: 'general　/ total' },
  { kanji: '索', meaning: 'look up' },
  { kanji: '納', meaning: 'to supply' },
  { kanji: '紛', meaning: 'ambiguous' },
  { kanji: '絹', meaning: 'silk' },
  { kanji: '系', meaning: 'group, tribe' },
  { kanji: '孫', meaning: 'grandchild' },
  { kanji: '係', meaning: 'be involved with' },
  { kanji: '干', meaning: 'dry out' },
  { kanji: '刊', meaning: 'edition' },
  { kanji: '用', meaning: 'utilize' },
  { kanji: '肝', meaning: 'liver' },
  { kanji: '芋', meaning: 'potato' },
  { kanji: '汗', meaning: 'sweat' },
  { kanji: '宇', meaning: 'cosmos' },
  { kanji: '千', meaning: 'thousand' },
  { kanji: '舌', meaning: 'tongue' },
  { kanji: '話', meaning: 'conversation' },
  { kanji: '活', meaning: 'vivid, lively' },
  { kanji: '辞', meaning: 'quit' },
  { kanji: '憩', meaning: 'break at work' },
  { kanji: '半', meaning: 'half' },
  { kanji: '判', meaning: 'judgement' },
  { kanji: '伴', meaning: 'accompany' },
  { kanji: '平', meaning: 'equal / level' },
  { kanji: '評', meaning: 'art or literary criticism' },
  { kanji: '呼', meaning: 'call to someone' },
  { kanji: '土', meaning: 'earth' },
  { kanji: '里', meaning: 'village' },
  { kanji: '量', meaning: 'quantity' },
  { kanji: '黒', meaning: 'black' },
  { kanji: '童', meaning: 'kid' },
  { kanji: '憧', meaning: 'yearn for' },
  { kanji: '埋', meaning: 'bury' },
  { kanji: '坊', meaning: 'boy / monk' },
  { kanji: '吐', meaning: 'puke' },
  { kanji: '塾', meaning: 'cram school' },
  { kanji: '士', meaning: 'samurai radical' },
  { kanji: '仕', meaning: 'work' },
  { kanji: '志', meaning: 'intention, volition' },
  { kanji: '吉', meaning: 'good omen' },
  { kanji: '詰', meaning: 'cram in' },
  { kanji: '結', meaning: 'bind' },
  { kanji: '誌', meaning: 'magazine' },
  { kanji: '老', meaning: 'get old' },
  { kanji: '孝', meaning: 'filial piety' },
  { kanji: '者', meaning: 'professional' },
  { kanji: '著', meaning: 'author' },
  { kanji: '緒', meaning: 'together' },
  { kanji: '諸', meaning: 'various' },
  { kanji: '署', meaning: 'government office' },
  { kanji: '暑', meaning: 'hot place' },
  { kanji: '煮', meaning: 'simmer/stew' },
  { kanji: '焦', meaning: 'char / scorch' },
  { kanji: '無', meaning: 'without' },
  { kanji: '維', meaning: 'upkeep' },
  { kanji: '唯', meaning: 'sole or only' },
  { kanji: '誰', meaning: 'who??' },
  { kanji: '準', meaning: 'prepare / criteria' },
  { kanji: '護', meaning: 'defend' },
  { kanji: '馬', meaning: 'horse' },
  { kanji: '止', meaning: 'stop' },
  { kanji: '雌', meaning: 'your Moms' },
  { kanji: '肯', meaning: 'consent' },
  { kanji: '歩', meaning: 'walk' },
  { kanji: '渉', meaning: 'interfere' },
  { kanji: '紫', meaning: 'purple' },
  { kanji: '足', meaning: 'foot/ be enough' },
  { kanji: '促', meaning: 'peer pressure' },
  { kanji: '踏', meaning: 'tread on' },
  { kanji: '正', meaning: 'correct' },
  { kanji: '是', meaning: 'fer shure' },
  { kanji: '定', meaning: 'plan' },
  { kanji: '証', meaning: 'proof' },
  { kanji: '歪', meaning: 'distort' },
  { kanji: '走', meaning: 'run' },
  { kanji: '超', meaning: 'exceed/ go over' },
  { kanji: '尺', meaning: 'R for ROCK' },
  { kanji: '駅', meaning: 'train station' },
  { kanji: '昼', meaning: 'noon' },
  { kanji: '訳', meaning: 'reason / translation' },
  { kanji: '沢', meaning: 'swamp / bling' },
  { kanji: '手', meaning: 'hand' },
  { kanji: '択', meaning: 'select' },
  { kanji: '推', meaning: 'infer' },
  { kanji: '描', meaning: 'depict' },
  { kanji: '提', meaning: 'submit a proposal' },
  { kanji: '払', meaning: 'pay' },
  { kanji: '批', meaning: 'call bullshit on' },
  { kanji: '指', meaning: 'finger / point at' },
  { kanji: '打', meaning: 'pound' },
  { kanji: '招', meaning: 'beckon' },
  { kanji: '拐', meaning: 'kidnap' },
  { kanji: '担', meaning: 'carry on your back' },
  { kanji: '接', meaning: 'directly contact' },
  { kanji: '拍', meaning: 'clap' },
  { kanji: '挿', meaning: 'insert' },
  { kanji: '看', meaning: 'observe/guard' },
  { kanji: '耳', meaning: 'ear' },
  { kanji: '取', meaning: 'take' },
  { kanji: '最', meaning: 'most' },
  { kanji: '撮', meaning: 'photo-shoot' },
  { kanji: '趣', meaning: 'hobby' },
  { kanji: '恥', meaning: 'disgrace' },
  { kanji: '聞', meaning: 'listen/ ask' },
  { kanji: '斤', meaning: 'axe' },
  { kanji: '折', meaning: 'fold' },
  { kanji: '丘', meaning: 'hill' },
  { kanji: '哲', meaning: 'philosophy' },
  { kanji: '誓', meaning: 'vow' },
  { kanji: '訴', meaning: 'accuse' },
  { kanji: '竹', meaning: 'bamboo' },
  { kanji: '筋', meaning: 'muscle' },
  { kanji: '簡', meaning: 'simplicity' },
  { kanji: '作', meaning: 'make' },
  { kanji: '昨', meaning: 'yesterday' },
  { kanji: '近', meaning: 'near' },
  { kanji: '辺', meaning: 'around here/around that time' },
  { kanji: '迫', meaning: 'press upon' },
  { kanji: '込', meaning: 'get crowded' },
  { kanji: '達', meaning: 'plural/delivery' },
  { kanji: '進', meaning: 'progress' },
  { kanji: '述', meaning: 'refer to' },
  { kanji: '木', meaning: 'tree' },
  { kanji: '林', meaning: 'grove' },
  { kanji: '森', meaning: 'forest' },
  { kanji: '本', meaning: 'book / the real' },
  { kanji: '体', meaning: 'body' },
  { kanji: '休', meaning: 'rest' },
  { kanji: '枠', meaning: 'boundary / limit' },
  { kanji: '析', meaning: 'analyze' },
  { kanji: '策', meaning: 'take measures' },
  { kanji: '刺', meaning: 'stab / business card' },
  { kanji: '新', meaning: 'new' },
  { kanji: '集', meaning: 'collect' },
  { kanji: '棚', meaning: 'shelf' },
  { kanji: '松', meaning: 'pine' },
  { kanji: '枯', meaning: 'wither' },
  { kanji: '相', meaning: 'partner' },
  { kanji: '箱', meaning: 'box' },
  { kanji: '想', meaning: 'idea/imagination' },
  { kanji: '禁', meaning: 'prohibition' },
  { kanji: '果', meaning: 'fruit　/ result' },
  { kanji: '課', meaning: 'section or lesson' },
  { kanji: '菓', meaning: 'sweets/pastry' },
  { kanji: '東', meaning: 'east' },
  { kanji: '練', meaning: 'practice' },
  { kanji: '案', meaning: 'guide/proposal' },
  { kanji: '杯', meaning: 'one cup of liquid' },
  { kanji: '膝', meaning: 'knee or lap' },
  { kanji: '保', meaning: 'guarantee/maintain' },
  { kanji: '繰', meaning: 'spin' },
  { kanji: '操', meaning: 'manipulate/ chastity' },
  { kanji: '染', meaning: 'dye' },
  { kanji: '雑', meaning: 'miscellaneous , random' },
  { kanji: '稚', meaning: 'childish' },
  { kanji: '和', meaning: 'peace/ Japan' },
  { kanji: '秘', meaning: 'secret' },
  { kanji: '私', meaning: 'me / private' },
  { kanji: '秒', meaning: 'one second' },
  { kanji: '移', meaning: 'transfer' },
  { kanji: '利', meaning: 'handy' },
  { kanji: '季', meaning: 'season' },
  { kanji: '委', meaning: 'member' },
  { kanji: '香', meaning: 'good smell' },
  { kanji: '秋', meaning: 'fall' },
  { kanji: '愁', meaning: 'sorrow' },
  { kanji: '末', meaning: 'the tip' },
  { kanji: '未', meaning: 'not yet' },
  { kanji: '妹', meaning: 'little sister' },
  { kanji: '味', meaning: 'flavor' },
  { kanji: '米', meaning: 'rice / America' },
  { kanji: '迷', meaning: 'perplexed' },
  { kanji: '謎', meaning: 'mystery' },
  { kanji: '断', meaning: 'decision/judgement/refuse' },
  { kanji: '継', meaning: 'succeed / inherit' },
  { kanji: '粘', meaning: 'be sticky' },
  { kanji: '粋', meaning: 'essence' },
  { kanji: '粒', meaning: 'grain' },
  { kanji: '粉', meaning: 'powder' },
  { kanji: '来', meaning: 'come/future' },
  { kanji: '番', meaning: 'number' },
  { kanji: '審', meaning: 'judge' },
  { kanji: '大', meaning: 'big' },
  { kanji: '奥', meaning: 'waaay in the back' },
  { kanji: '奇', meaning: 'strange' },
  { kanji: '寄', meaning: 'get close' },
  { kanji: '臭', meaning: 'stinky odor' },
  { kanji: '奮', meaning: 'get worked up' },
  { kanji: '器', meaning: 'instrument' },
  { kanji: '突', meaning: 'thrust' },
  { kanji: '央', meaning: 'central' },
  { kanji: '映', meaning: 'project, reflect' },
  { kanji: '英', meaning: 'heroic' },
  { kanji: '犬', meaning: 'dog' },
  { kanji: '伏', meaning: 'lay face down' },
  { kanji: '黙', meaning: 'shut up' },
  { kanji: '然', meaning: 'nature' },
  { kanji: '燃', meaning: 'burn' },
  { kanji: '太', meaning: 'fat' },
  { kanji: '駄', meaning: 'bad quality' },
  { kanji: '漢', meaning: 'Chinese' },
  { kanji: '難', meaning: 'difficult' },
  { kanji: '勤', meaning: 'be employed at' },
  { kanji: '嘆', meaning: 'lament, sigh' },
  { kanji: '模', meaning: 'model' },
  { kanji: '墓', meaning: 'grave' },
  { kanji: '暮', meaning: 'make a living' },
  { kanji: '募', meaning: 'recruit' },
  { kanji: '幕', meaning: 'curtain' },
  { kanji: '漠', meaning: 'desert' },
  { kanji: '因', meaning: 'origin' },
  { kanji: '恩', meaning: 'kindness' },
  { kanji: '菌', meaning: 'bacteria' },
  { kanji: '困', meaning: 'trouble' },
  { kanji: '囚', meaning: 'prisoner' },
  { kanji: '回', meaning: 'rotate / times' },
  { kanji: '固', meaning: 'hard' },
  { kanji: '個', meaning: 'individual' },
  { kanji: '井', meaning: 'well' },
  { kanji: '囲', meaning: 'surround' },
  { kanji: '丼', meaning: 'beef bowl' },
  { kanji: '王', meaning: 'king' },
  { kanji: '玉', meaning: 'ball' },
  { kanji: '国', meaning: 'country' },
  { kanji: '宝', meaning: 'treasure' },
  { kanji: '理', meaning: 'reason' },
  { kanji: '任', meaning: 'have responsibility for' },
  { kanji: '妊', meaning: 'pregnant' },
  { kanji: '皇', meaning: 'emperor' },
  { kanji: '望', meaning: 'desire' },
  { kanji: '聖', meaning: 'holy' },
  { kanji: '程', meaning: 'extent' },
  { kanji: '主', meaning: 'master/mainly' },
  { kanji: '契', meaning: 'contract' },
  { kanji: '喫', meaning: 'enjoy a drink and a smoke' },
  { kanji: '潔', meaning: 'honorable' },
  { kanji: '注', meaning: 'pour / be careful' },
  { kanji: '柱', meaning: 'pillar' },
  { kanji: '住', meaning: 'dwell' },
  { kanji: '駐', meaning: 'stop at' },
  { kanji: '害', meaning: 'damage' },
  { kanji: '割', meaning: 'divide' },
  { kanji: '素', meaning: 'element' },
  { kanji: '憲', meaning: 'constitution' },
  { kanji: '青', meaning: 'blue' },
  { kanji: '請', meaning: 'request' },
  { kanji: '清', meaning: 'pure' },
  { kanji: '精', meaning: 'spirit' },
  { kanji: '晴', meaning: 'weather get good now' },
  { kanji: '情', meaning: 'emotion' },
  { kanji: '生', meaning: 'life / birth' },
  { kanji: '星', meaning: 'star' },
  { kanji: '性', meaning: 'sex / essential nature' },
  { kanji: '姓', meaning: 'family name' },
  { kanji: '朱', meaning: 'vermilion' },
  { kanji: '株', meaning: 'share, stock' },
  { kanji: '遊', meaning: 'play around' },
  { kanji: '称', meaning: 'symmetry' },
  { kanji: '乙', meaning: 'second rank / girl' },
  { kanji: '乾', meaning: 'dessicate' },
  { kanji: '母', meaning: 'your Moms' },
  { kanji: '毒', meaning: 'poison/ addict' },
  { kanji: '毎', meaning: 'every' },
  { kanji: '梅', meaning: 'plum' },
  { kanji: '海', meaning: 'ocean' },
  { kanji: '悔', meaning: 'regret' },
  { kanji: '侮', meaning: 'despise' },
  { kanji: '中', meaning: 'middle' },
  { kanji: '忠', meaning: 'loyalty' },
  { kanji: '患', meaning: 'medical patient' },
  { kanji: '仲', meaning: 'friendship' },
  { kanji: '虫', meaning: 'insizzect' },
  { kanji: '蛇', meaning: 'snake' },
  { kanji: '蚊', meaning: 'mosquito' },
  { kanji: '騒', meaning: 'make noise' },
  { kanji: '属', meaning: 'genus/affiliation' },
  { kanji: '居', meaning: 'live' },
  { kanji: '尼', meaning: 'nun' },
  { kanji: '泥', meaning: 'mud' },
  { kanji: '尿', meaning: 'urine' },
  { kanji: '尻', meaning: 'butt' },
  { kanji: '刷', meaning: 'print' },
  { kanji: '戸', meaning: 'door' },
  { kanji: '所', meaning: 'area / attribute' },
  { kanji: '肩', meaning: 'shoulder' },
  { kanji: '雇', meaning: 'hire' },
  { kanji: '房', meaning: 'wife/cluster' },
  { kanji: '戻', meaning: 'return' },
  { kanji: '涙', meaning: 'teardrop' },
  { kanji: '毛', meaning: 'fur' },
  { kanji: '尾', meaning: 'tail' },
  { kanji: '革', meaning: 'leather/revolution' },
  { kanji: '靴', meaning: 'shoe' },
  { kanji: '甘', meaning: 'sweet' },
  { kanji: '某', meaning: 'a certain' },
  { kanji: '謀', meaning: 'plot' },
  { kanji: '見', meaning: 'look' },
  { kanji: '寛', meaning: 'leniency' },
  { kanji: '焼', meaning: 'roast / grill' },
  { kanji: '境', meaning: 'border' },
  { kanji: '現', meaning: 'reality' },
  { kanji: '親', meaning: 'parents/kindness' },
  { kanji: '兄', meaning: 'older brother' },
  { kanji: '克', meaning: 'overcome' },
  { kanji: '況', meaning: 'condition' },
  { kanji: '競', meaning: 'contest' },
  { kanji: '児', meaning: 'baby' },
  { kanji: '貝', meaning: 'shellfish (money)' },
  { kanji: '買', meaning: 'buy' },
  { kanji: '憤', meaning: 'get indignant' },
  { kanji: '噴', meaning: 'spew' },
  { kanji: '貨', meaning: 'cargo' },
  { kanji: '貧', meaning: 'poverty' },
  { kanji: '貯', meaning: 'save up' },
  { kanji: '賭', meaning: 'bet or stake' },
  { kanji: '質', meaning: 'quality' },
  { kanji: '賃', meaning: 'rent money' },
  { kanji: '貞', meaning: 'chastity' },
  { kanji: '偵', meaning: 'detective' },
  { kanji: '員', meaning: 'clerk' },
  { kanji: '損', meaning: 'harm' },
  { kanji: '則', meaning: 'rule' },
  { kanji: '側', meaning: 'side of something' },
  { kanji: '測', meaning: 'scientific measurement' },
  { kanji: '貫', meaning: 'pierce' },
  { kanji: '慣', meaning: 'adapt' },
  { kanji: '責', meaning: 'condemn' },
  { kanji: '績', meaning: 'achievements' },
  { kanji: '積', meaning: 'pile up' },
  { kanji: '貴', meaning: 'exalted' },
  { kanji: '遺', meaning: 'bequeath' },
  { kanji: '兵', meaning: 'soldier' },
  { kanji: '浜', meaning: 'beach' },
  { kanji: '負', meaning: 'lose' },
  { kanji: '魚', meaning: 'fish' },
  { kanji: '角', meaning: 'horn/corner' },
  { kanji: '触', meaning: 'touch' },
  { kanji: '売', meaning: 'sell' },
  { kanji: '続', meaning: 'continue' },
  { kanji: '読', meaning: 'read' },
  { kanji: '窓', meaning: 'window' },
  { kanji: '探', meaning: 'look for' },
  { kanji: '深', meaning: 'deep' },
  { kanji: '具', meaning: 'tool' },
  { kanji: '元', meaning: 'original' },
  { kanji: '完', meaning: 'complete' },
  { kanji: '西', meaning: 'west' },
  { kanji: '票', meaning: 'ballot' },
  { kanji: '標', meaning: 'sign, mark' },
  { kanji: '漂', meaning: 'drift' },
  { kanji: '酒', meaning: 'liquor' },
  { kanji: '酔', meaning: 'drunk' },
  { kanji: '価', meaning: 'value' },
  { kanji: '要', meaning: 'important' },
  { kanji: '腰', meaning: 'waist' },
  { kanji: '煙', meaning: 'smoky' },
  { kanji: '才', meaning: 'skill / age' },
  { kanji: '財', meaning: 'loot' },
  { kanji: '材', meaning: 'raw materials' },
  { kanji: '閉', meaning: 'close store' },
  { kanji: '夫', meaning: 'husband' },
  { kanji: '賛', meaning: 'agree' },
  { kanji: '替', meaning: 'substitute' },
  { kanji: '潜', meaning: 'lurk' },
  { kanji: '規', meaning: 'criteria' },
  { kanji: '挟', meaning: 'pinch' },
  { kanji: '巣', meaning: 'habitat' },
  { kanji: '光', meaning: 'shining' },
  { kanji: '単', meaning: 'merely' },
  { kanji: '桜', meaning: 'sakura' },
  { kanji: '肖', meaning: 'carrot' },
  { kanji: '削', meaning: 'whittle down' },
  { kanji: '消', meaning: 'erase' },
  { kanji: '菜', meaning: 'vegetable' },
  { kanji: '浮', meaning: 'float' },
  { kanji: '受', meaning: 'receive' },
  { kanji: '妥', meaning: 'compromise' },
  { kanji: '授', meaning: 'instruct' },
  { kanji: '採', meaning: 'gather' },
  { kanji: '久', meaning: 'been a long time' },
  { kanji: '各', meaning: 'each' },
  { kanji: '愛', meaning: 'love' },
  { kanji: '客', meaning: 'customer' },
  { kanji: '落', meaning: 'fall,drop' },
  { kanji: '格', meaning: 'character, aspect' },
  { kanji: '絡', meaning: 'get entangled' },
  { kanji: '略', meaning: 'abbreviation' },
  { kanji: '路', meaning: 'road' },
  { kanji: '条', meaning: 'clause' },
  { kanji: '麦', meaning: 'barley' },
  { kanji: '酸', meaning: 'sour' },
  { kanji: '秀', meaning: 'excel' },
  { kanji: '誘', meaning: 'invite / entice' },
  { kanji: '透', meaning: 'transparent' },
  { kanji: '携', meaning: 'carry in hand' },
  { kanji: '及', meaning: 'reach / amount to' },
  { kanji: '吸', meaning: 'suck' },
  { kanji: '級', meaning: 'level' },
  { kanji: '扱', meaning: 'treatment' },
  { kanji: '穏', meaning: 'tranquil' },
  { kanji: '侵', meaning: 'perpetrate' },
  { kanji: '浸', meaning: 'immerse' },
  { kanji: '緑', meaning: 'green' },
  { kanji: '急', meaning: 'urgent' },
  { kanji: '当', meaning: 'hit the target' },
  { kanji: '婦', meaning: 'housewife / lady' },
  { kanji: '掃', meaning: 'sweep' },
  { kanji: '帰', meaning: 'go back home' },
  { kanji: '帝', meaning: 'foreign emperor' },
  { kanji: '締', meaning: 'tighten' },
  { kanji: '躍', meaning: 'jump' },
  { kanji: '濯', meaning: 'rinse' },
  { kanji: '曜', meaning: 'day of the week' },
  { kanji: '工', meaning: 'craft or industry' },
  { kanji: '空', meaning: 'air' },
  { kanji: '控', meaning: 'abstain' },
  { kanji: '紅', meaning: 'dark lipstick red color' },
  { kanji: '功', meaning: 'success' },
  { kanji: '巧', meaning: 'adroit' },
  { kanji: '与', meaning: 'bestow' },
  { kanji: '写', meaning: 'copy' },
  { kanji: '汚', meaning: 'dirty' },
  { kanji: '極', meaning: 'extreme' },
  { kanji: '誇', meaning: 'be proud of' },
  { kanji: '号', meaning: 'ID number' },
  { kanji: '考', meaning: 'consider' },
  { kanji: '拷', meaning: 'torture' },
  { kanji: '式', meaning: 'ritual' },
  { kanji: '拭', meaning: 'wipe' },
  { kanji: '試', meaning: 'attempt to do' },
  { kanji: '武', meaning: 'military' },
  { kanji: '代', meaning: 'generation / instead of' },
  { kanji: '貸', meaning: 'lend' },
  { kanji: '閥', meaning: 'clique' },
  { kanji: '惑', meaning: 'be misguided or tempted' },
  { kanji: '我', meaning: 'we' },
  { kanji: '賊', meaning: 'bandit' },
  { kanji: '域', meaning: 'region' },
  { kanji: '戦', meaning: 'fight' },
  { kanji: '栽', meaning: 'cultivate' },
  { kanji: '幾', meaning: 'how much?' },
  { kanji: '機', meaning: 'machine' },
  { kanji: '職', meaning: 'employment' },
  { kanji: '織', meaning: 'organization / weave' },
  { kanji: '識', meaning: 'be conscious' },
  { kanji: '区', meaning: 'ward' },
  { kanji: '駆', meaning: 'gallop' },
  { kanji: '巨', meaning: 'giant super huge' },
  { kanji: '拒', meaning: 'repel' },
  { kanji: '距', meaning: 'distance' },
  { kanji: '臣', meaning: 'vassal' },
  { kanji: '堅', meaning: 'solid, steadfast' },
  { kanji: '緊', meaning: 'tense' },
  { kanji: '賢', meaning: 'clever' },
  { kanji: '覧', meaning: 'view' },
  { kanji: '臨', meaning: 'to confront' },
  { kanji: '姫', meaning: 'princess' },
  { kanji: '匹', meaning: 'small animal' },
  { kanji: '匠', meaning: 'artisan' },
  { kanji: '四', meaning: 'the numeral 4' },
  { kanji: '喚', meaning: 'exclaim' },
  { kanji: '換', meaning: 'exchange' },
  { kanji: '欠', meaning: 'lack' },
  { kanji: '欧', meaning: 'Europe' },
  { kanji: '歌', meaning: 'sing' },
  { kanji: '吹', meaning: 'blow' },
  { kanji: '炊', meaning: 'cook rice' },
  { kanji: '数', meaning: 'integer, to count' },
  { kanji: '枚', meaning: 'counter for flat objects' },
  { kanji: '敏', meaning: 'agile / sensitive' },
  { kanji: '敗', meaning: 'be defeated' },
  { kanji: '故', meaning: 'breakdown, accident' },
  { kanji: '政', meaning: 'politics' },
  { kanji: '放', meaning: 'release' },
  { kanji: '教', meaning: 'teach' },
  { kanji: '激', meaning: 'intense' },
  { kanji: '繁', meaning: 'multiple, many' },
  { kanji: '攻', meaning: 'attack' },
  { kanji: '敵', meaning: 'enemy' },
  { kanji: '適', meaning: 'suitable' },
  { kanji: '滴', meaning: 'drip' },
  { kanji: '摘', meaning: 'pluck' },
  { kanji: '己', meaning: 'myself' },
  { kanji: '改', meaning: 'renew / improve' },
  { kanji: '起', meaning: 'wake up / occur' },
  { kanji: '紀', meaning: 'century' },
  { kanji: '記', meaning: 'diary' },
  { kanji: '配', meaning: 'distribute' },
  { kanji: '求', meaning: 'demand/ask' },
  { kanji: '救', meaning: 'rescue' },
  { kanji: '球', meaning: 'sphere' },
  { kanji: '厳', meaning: 'strict' },
  { kanji: '励', meaning: 'diligence' },
  { kanji: '歴', meaning: 'chronicle' },
  { kanji: '厚', meaning: 'thick' },
  { kanji: '圧', meaning: 'pressure' },
  { kanji: '粧', meaning: 'makeup' },
  { kanji: '備', meaning: 'furnish' },
  { kanji: '灰', meaning: 'ash/ gray' },
  { kanji: '産', meaning: 'childbirth, production of things' },
  { kanji: '原', meaning: 'original/ high plain' },
  { kanji: '源', meaning: 'hot spring　/ origin' },
  { kanji: '反', meaning: 'anti' },
  { kanji: '返', meaning: 'return or respond' },
  { kanji: '坂', meaning: 'slope' },
  { kanji: '板', meaning: 'plank' },
  { kanji: '仮', meaning: 'provisional' },
  { kanji: '販', meaning: 'transaction' },
  { kanji: '成', meaning: 'become' },
  { kanji: '誠', meaning: 'sincerity' },
  { kanji: '越', meaning: 'go beyond' },
  { kanji: '蔵', meaning: 'traditional storehouse' },
  { kanji: '臓', meaning: 'internal organ' },
  { kanji: '歳', meaning: 'years old' },
  { kanji: '滅', meaning: 'annihilate' },
  { kanji: '威', meaning: 'terrible majesty' },
  { kanji: '城', meaning: 'castle' },
  { kanji: '幻', meaning: 'illusion' },
  { kanji: '気', meaning: 'mood' },
  { kanji: '決', meaning: 'decide' },
  { kanji: '快', meaning: 'pleasant' },
  { kanji: '獣', meaning: 'beast' },
  { kanji: '減', meaning: 'decrease' },
  { kanji: '感', meaning: 'feeling' },
  { kanji: '憾', meaning: 'regrettable' },
  { kanji: '同', meaning: 'same' },
  { kanji: '筒', meaning: 'cylinder /pipe' },
  { kanji: '司', meaning: 'administer' },
  { kanji: '伺', meaning: 'formal visit / question' },
  { kanji: '詞', meaning: 'part of speech' },
  { kanji: '旅', meaning: 'trip' },
  { kanji: '派', meaning: 'faction/bling' },
  { kanji: '脈', meaning: 'vein' },
  { kanji: '遠', meaning: 'far' },
  { kanji: '園', meaning: 'public park' },
  { kanji: '環', meaning: 'environment' },
  { kanji: '表', meaning: 'express' },
  { kanji: '衣', meaning: 'cloth' },
  { kanji: '依', meaning: 'depend on' },
  { kanji: '袋', meaning: 'sack' },
  { kanji: '裁', meaning: 'trial' },
  { kanji: '褒', meaning: 'praise' },
  { kanji: '裏', meaning: 'backside' },
  { kanji: '哀', meaning: 'pitiful' },
  { kanji: '衰', meaning: 'decline,wane' },
  { kanji: '良', meaning: 'good' },
  { kanji: '娘', meaning: 'daughter' },
  { kanji: '退', meaning: 'retreat' },
  { kanji: '浪', meaning: 'wavelike' },
  { kanji: '眼', meaning: 'eyeball' },
  { kanji: '恨', meaning: 'hold a grudge' },
  { kanji: '根', meaning: 'root' },
  { kanji: '限', meaning: 'limit' },
  { kanji: '郷', meaning: 'one\\'s hometown' },
  { kanji: '響', meaning: 'echo' },
  { kanji: '階', meaning: 'story of a building' },
  { kanji: '障', meaning: 'impede' },
  { kanji: '院', meaning: 'institution' },
  { kanji: '防', meaning: 'ward off' },
  { kanji: '陥', meaning: 'entrapped' },
  { kanji: '都', meaning: 'major city' },
  { kanji: '隠', meaning: 'hide' },
  { kanji: '部', meaning: 'section' },
  { kanji: '剖', meaning: 'dissect' },
  { kanji: '倍', meaning: 'double' },
  { kanji: '壮', meaning: 'epic!!!' },
  { kanji: '装', meaning: 'dress up' },
  { kanji: '状', meaning: 'circumstance' },
  { kanji: '寝', meaning: 'go to bed' },
  { kanji: '北', meaning: 'north' },
  { kanji: '背', meaning: 'stature / back of the body' },
  { kanji: '制', meaning: 'system' },
  { kanji: '製', meaning: 'mass production' },
  { kanji: '告', meaning: 'inform' },
  { kanji: '造', meaning: 'produce' },
  { kanji: '酷', meaning: 'horrendous' },
  { kanji: '先', meaning: 'earlier/ the tip' },
  { kanji: '洗', meaning: 'wash' },
  { kanji: '面', meaning: 'front surface / face' },
  { kanji: '百', meaning: 'hundred' },
  { kanji: '憂', meaning: 'grieve' },
  { kanji: '優', meaning: 'kindhearted/excel' },
  { kanji: '宿', meaning: 'lodge at' },
  { kanji: '縮', meaning: 'contract / shrink' },
  { kanji: '石', meaning: 'rock' },
  { kanji: '砂', meaning: 'sand' },
  { kanji: '砕', meaning: 'pulverize' },
  { kanji: '礎', meaning: 'foundation' },
  { kanji: '山', meaning: 'mountain' },
  { kanji: '岩', meaning: 'boulder' },
  { kanji: '帯', meaning: 'belt' },
  { kanji: '滞', meaning: 'delay / be overdue' },
  { kanji: '催', meaning: 'sponsor' },
  { kanji: '崩', meaning: 'collapse' },
  { kanji: '密', meaning: 'hard to see' },
  { kanji: '幽', meaning: 'occult' },
  { kanji: '岸', meaning: 'shore' },
  { kanji: '炭', meaning: 'carbon' },
  { kanji: '岳', meaning: 'mount' },
  { kanji: '鳥', meaning: 'bird' },
  { kanji: '島', meaning: 'island' },
  { kanji: '鳴', meaning: 'animal cry' },
  { kanji: '豆', meaning: 'bean' },
  { kanji: '喜', meaning: 'rejoice' },
  { kanji: '嬉', meaning: 'stoked' },
  { kanji: '頭', meaning: 'head' },
  { kanji: '夏', meaning: 'summer' },
  { kanji: '願', meaning: 'beseech' },
  { kanji: '頑', meaning: 'stubborn' },
  { kanji: '頃', meaning: 'around that time' },
  { kanji: '頂', meaning: 'summit/climax' },
  { kanji: '額', meaning: 'amount of money / forehead' },
  { kanji: '類', meaning: 'category,type' },
  { kanji: '題', meaning: 'topic' },
  { kanji: '顧', meaning: 'look back on' },
  { kanji: '傾', meaning: 'lean' },
  { kanji: '項', meaning: 'item/paragraph' },
  { kanji: '川', meaning: 'river' },
  { kanji: '順', meaning: 'sequence' },
  { kanji: '州', meaning: 'state' },
  { kanji: '訓', meaning: 'kunyomi' },
  { kanji: '荒', meaning: 'go wild / rough' },
  { kanji: '慌', meaning: 'be in a rush / freaked out' },
  { kanji: '首', meaning: 'neck' },
  { kanji: '道', meaning: 'street' },
  { kanji: '税', meaning: 'tax' },
  { kanji: '説', meaning: 'explain' },
  { kanji: '脱', meaning: 'get naked' },
  { kanji: '磁', meaning: 'magnet' },
  { kanji: '羊', meaning: 'sheep' },
  { kanji: '南', meaning: 'south' },
  { kanji: '美', meaning: 'beauty' },
  { kanji: '鮮', meaning: 'fresh' },
  { kanji: '詳', meaning: 'expert' },
  { kanji: '洋', meaning: 'Pacific Ocean / the West' },
  { kanji: '遅', meaning: 'slow / late' },
  { kanji: '着', meaning: 'wear / arrive' },
  { kanji: '養', meaning: 'cultivate, rear' },
  { kanji: '義', meaning: 'righteousness' },
  { kanji: '儀', meaning: 'politeness' },
  { kanji: '議', meaning: 'discussion' },
  { kanji: '様', meaning: 'important person' },
  { kanji: '天', meaning: 'heaven' },
  { kanji: '添', meaning: 'append' },
  { kanji: '笑', meaning: 'laugh' },
  { kanji: '呑', meaning: 'chug' },
  { kanji: '送', meaning: 'send' },
  { kanji: '咲', meaning: 'bloom' },
  { kanji: '関', meaning: 'connected to' },
  { kanji: '巻', meaning: 'roll up' },
  { kanji: '圏', meaning: 'range / area of influence' },
  { kanji: '券', meaning: 'certificate, cupon' },
  { kanji: '勝', meaning: 'win' },
  { kanji: '弓', meaning: 'bow' },
  { kanji: '弟', meaning: 'younger brother' },
  { kanji: '第', meaning: 'rank or number in series' },
  { kanji: '沸', meaning: 'boil water' },
  { kanji: '費', meaning: 'expenses' },
  { kanji: '強', meaning: 'burly' },
  { kanji: '引', meaning: 'pull' },
  { kanji: '弾', meaning: 'bullet / play guitar / bounce' },
  { kanji: '赤', meaning: 'red' },
  { kanji: '湾', meaning: 'bay' },
  { kanji: '跡', meaning: 'vestiges' },
  { kanji: '恋', meaning: 'passion' },
  { kanji: '変', meaning: 'change' },
  { kanji: '長', meaning: 'long / boss' },
  { kanji: '張', meaning: 'stretch' },
  { kanji: '帳', meaning: 'notebook' },
  { kanji: '険', meaning: 'steep / risky' },
  { kanji: '検', meaning: 'investigate' },
  { kanji: '倹', meaning: 'thrifty' },
  { kanji: '剣', meaning: 'saber' },
  { kanji: '験', meaning: 'test' },
  { kanji: '金', meaning: 'gold' },
  { kanji: '鋭', meaning: 'sharp' },
  { kanji: '錆', meaning: 'rust' },
  { kanji: '録', meaning: 'record' },
  { kanji: '鏡', meaning: 'mirror' },
  { kanji: '鎖', meaning: 'shut/chain' },
  { kanji: '銀', meaning: 'silver' },
  { kanji: '針', meaning: 'needle' },
  { kanji: '銅', meaning: 'bronze' },
  { kanji: '茶', meaning: 'tea' },
  { kanji: '傘', meaning: 'umbrella' },
  { kanji: '全', meaning: 'all' },
  { kanji: '企', meaning: 'scheme' },
  { kanji: '食', meaning: 'eat' },
  { kanji: '飲', meaning: 'drink' },
  { kanji: '飾', meaning: 'decorate' },
  { kanji: '飯', meaning: 'rice / meal' },
  { kanji: '飼', meaning: 'keep a pet' },
  { kanji: '幹', meaning: 'trunk' },
  { kanji: '舎', meaning: 'stable' },
  { kanji: '捨', meaning: 'throw away' },
  { kanji: '余', meaning: 'excess' },
  { kanji: '塗', meaning: 'paint' },
  { kanji: '途', meaning: 'on the way' },
  { kanji: '除', meaning: 'exclude' },
  { kanji: '倉', meaning: 'storage' },
  { kanji: '創', meaning: 'originate / creative' },
  { kanji: '介', meaning: 'introduce / intervene' },
  { kanji: '界', meaning: 'the world' },
  { kanji: '合', meaning: 'to suit' },
  { kanji: '給', meaning: 'provide' },
  { kanji: '塔', meaning: 'tower' },
  { kanji: '拾', meaning: 'pick up off the ground' },
  { kanji: '搭', meaning: 'board' },
  { kanji: '答', meaning: 'answer' },
  { kanji: 'ラ', meaning: 'rambo' },
  { kanji: '今', meaning: 'now' },
  { kanji: '含', meaning: 'include' },
  { kanji: '念', meaning: 'concern' },
  { kanji: '令', meaning: 'command' },
  { kanji: '鈴', meaning: 'tiny electric bell or buzzer' },
  { kanji: '領', meaning: 'territory' },
  { kanji: '命', meaning: 'life' },
  { kanji: '冷', meaning: 'cold thing' },
  { kanji: '凍', meaning: 'to freeze' },
  { kanji: '尽', meaning: 'exhaust, use up' },
  { kanji: '冬', meaning: 'winter' },
  { kanji: '終', meaning: 'end' },
  { kanji: '次', meaning: 'next' },
  { kanji: '姿', meaning: 'someone\\'s shape, body, form' },
  { kanji: '資', meaning: 'capital (as in $$$)' },
  { kanji: '寒', meaning: 'cold' },
  { kanji: '奏', meaning: 'musical performance' },
  { kanji: '春', meaning: 'spring /sexy' },
  { kanji: '棒', meaning: 'pole' },
  { kanji: '実', meaning: 'truth' },
  { kanji: '冊', meaning: 'counter for books' },
  { kanji: '扁', meaning: 'flat' },
  { kanji: '編', meaning: 'knit' },
  { kanji: '騙', meaning: 'deceive' },
  { kanji: '偏', meaning: 'be inclined' },
  { kanji: '論', meaning: 'make a case for' },
  { kanji: '倫', meaning: 'principles' },
  { kanji: '寸', meaning: 'glue' },
  { kanji: '付', meaning: 'stick to' },
  { kanji: '附', meaning: 'attachment' },
  { kanji: '討', meaning: 'attack/discuss' },
  { kanji: '奪', meaning: 'steal by force' },
  { kanji: '守', meaning: 'protect' },
  { kanji: '団', meaning: 'group' },
  { kanji: '符', meaning: 'ticket' },
  { kanji: '村', meaning: 'hicktown' },
  { kanji: '寿', meaning: 'lifespan/sushi' },
  { kanji: '慰', meaning: 'console' },
  { kanji: '尋', meaning: 'ask' },
  { kanji: '導', meaning: 'lead' },
  { kanji: '闘', meaning: 'struggle' },
  { kanji: '寺', meaning: 'temple' },
  { kanji: '詩', meaning: 'poem' },
  { kanji: '時', meaning: 'time' },
  { kanji: '持', meaning: 'hold' },
  { kanji: '侍', meaning: 'samurai kanji' },
  { kanji: '等', meaning: 'equal /etc./plural' },
  { kanji: '尊', meaning: 'esteem' },
  { kanji: '噂', meaning: 'rumor' },
  { kanji: '父', meaning: 'dad' },
  { kanji: '交', meaning: 'combine' },
  { kanji: '対', meaning: 'against' },
  { kanji: '校', meaning: 'school' },
  { kanji: '郊', meaning: 'suburb' },
  { kanji: '効', meaning: 'effective' },
  { kanji: '絞', meaning: 'wring out / strangle' },
  { kanji: '専', meaning: 'specialty' },
  { kanji: '博', meaning: 'museum　/extensive' },
  { kanji: '縛', meaning: 'tie up' },
  { kanji: '薄', meaning: 'weak or thin' },
  { kanji: '演', meaning: 'performance' },
  { kanji: '恵', meaning: 'do a favor' },
  { kanji: '敷', meaning: 'lay out / site' },
  { kanji: '画', meaning: 'a drawing' },
  { kanji: '両', meaning: 'both' },
  { kanji: '満', meaning: 'full' },
  { kanji: '出', meaning: 'pull out / hand over' },
  { kanji: '屈', meaning: 'yield, get out of the way' },
  { kanji: '掘', meaning: 'dig' },
  { kanji: '缶', meaning: 'can, like \\'canned beef\\'' },
  { kanji: '揺', meaning: 'sway, joggle' },
  { kanji: '世', meaning: 'society' },
  { kanji: '葉', meaning: 'leaf' },
  { kanji: '喋', meaning: 'speak' },
  { kanji: '歯', meaning: 'tooth' },
  { kanji: '噛', meaning: 'chew, bite' },
  { kanji: '齢', meaning: 'stage of life' },
  { kanji: '凶', meaning: 'terrible' },
  { kanji: '脳', meaning: 'brain' },
  { kanji: '悩', meaning: 'worry' },
  { kanji: '離', meaning: 'divorce / physical distance between things' },
  { kanji: '矢', meaning: 'arrow' },
  { kanji: '疑', meaning: 'doubt' },
  { kanji: '擬', meaning: 'sham' },
  { kanji: '短', meaning: 'short / brief' },
  { kanji: '医', meaning: 'doctor' },
  { kanji: '族', meaning: 'family' },
  { kanji: '候', meaning: 'climate/candidate' },
  { kanji: '知', meaning: 'know' },
  { kanji: '失', meaning: 'miss out on' },
  { kanji: '鉄', meaning: 'iron' },
  { kanji: '観', meaning: 'point of view' },
  { kanji: '勧', meaning: 'recommend' },
  { kanji: '権', meaning: 'rights' },
  { kanji: '確', meaning: 'make certain' },
  { kanji: '車', meaning: 'car' },
  { kanji: '重', meaning: 'heavy / overlap' },
  { kanji: '垂', meaning: 'drip, dangle' },
  { kanji: '乗', meaning: 'ride a vehicle' },
  { kanji: '陣', meaning: 'base' },
  { kanji: '輪', meaning: 'ring/tire' },
  { kanji: '軒', meaning: 'counter for shops' },
  { kanji: '較', meaning: 'evaluate' },
  { kanji: '軟', meaning: 'soft' },
  { kanji: '載', meaning: 'appear in print' },
  { kanji: '軍', meaning: 'army' },
  { kanji: '揮', meaning: 'brandish' },
  { kanji: '連', meaning: 'take with / inform of' },
  { kanji: '運', meaning: 'carry / luck' },
  { kanji: '輝', meaning: 'dazzle' },
  { kanji: '華', meaning: 'flamboyant' },
  { kanji: '睡', meaning: 'sleep' },
  { kanji: '郵', meaning: 'mail' },
  { kanji: '剰', meaning: 'excessive' },
  { kanji: '種', meaning: 'seed　/ type or kind' },
  { kanji: '動', meaning: 'movement' },
  { kanji: '働', meaning: 'to do your job' },
  { kanji: '腫', meaning: 'swell' },
  { kanji: '非', meaning: 'injustice / mistake' },
  { kanji: '輩', meaning: 'older or younger colleague' },
  { kanji: '悲', meaning: 'sad' },
  { kanji: '罪', meaning: 'sin' },
  { kanji: '俳', meaning: 'actor' },
  { kanji: '排', meaning: 'eliminate' },
  { kanji: '軽', meaning: 'lightweight' },
  { kanji: '経', meaning: 'experience' },
  { kanji: '怪', meaning: 'suspicious' },
  { kanji: '友', meaning: 'friend' },
  { kanji: '抜', meaning: 'extract' },
  { kanji: '雄', meaning: 'male animal or hero' },
  { kanji: '布', meaning: 'fabric' },
  { kanji: '希', meaning: 'request / uncommon' },
  { kanji: '怖', meaning: 'scary' },
  { kanji: '右', meaning: 'right' },
  { kanji: '左', meaning: 'left' },
  { kanji: '若', meaning: 'young' },
  { kanji: '有', meaning: 'exist' },
  { kanji: '堕', meaning: 'corrupt' },
  { kanji: '賄', meaning: 'bribe　/ provide capital to' },
  { kanji: '差', meaning: 'discriminate' },
  { kanji: '在', meaning: 'be real' },
  { kanji: '存', meaning: 'be aware of' },
  { kanji: '片', meaning: 'fragment' },
  { kanji: '版', meaning: 'printing plate' },
  { kanji: '暖', meaning: 'warm place' },
  { kanji: '援', meaning: 'assist' },
  { kanji: '緩', meaning: 'become loose / abate' },
  { kanji: '髪', meaning: 'hair' },
  { kanji: '彩', meaning: 'hue' },
  { kanji: '影', meaning: 'shadow' },
  { kanji: '顔', meaning: 'face' },
  { kanji: '参', meaning: 'admit defeat / visit' },
  { kanji: '修', meaning: 'master a skill' },
  { kanji: '惨', meaning: 'wretched' },
  { kanji: '膨', meaning: 'bulge' },
  { kanji: '珍', meaning: 'very rare' },
  { kanji: '診', meaning: 'diagnose' },
  { kanji: '廊', meaning: 'corridor' },
  { kanji: '磨', meaning: 'to brush' },
  { kanji: '腐', meaning: 'rot' },
  { kanji: '応', meaning: 'react' },
  { kanji: '府', meaning: 'government' },
  { kanji: '庁', meaning: 'metropolitan government' },
  { kanji: '庫', meaning: 'warehouse' },
  { kanji: '店', meaning: 'shop' },
  { kanji: '座', meaning: 'sit' },
  { kanji: '床', meaning: 'floor' },
  { kanji: '麻', meaning: 'mah jongg / ganja' },
  { kanji: '摩', meaning: 'friction' },
  { kanji: '広', meaning: 'wide' },
  { kanji: '拡', meaning: 'to expand' },
  { kanji: '庶', meaning: 'populist' },
  { kanji: '席', meaning: 'seat' },
  { kanji: '度', meaning: 'times' },
  { kanji: '渡', meaning: 'pass by' },
  { kanji: '鬼', meaning: 'demon' },
  { kanji: '魔', meaning: 'devil' },
  { kanji: '魅', meaning: 'enchant' },
  { kanji: '醜', meaning: 'ugly' },
  { kanji: '塊', meaning: 'clump' },
  { kanji: '卑', meaning: 'despicable' },
  { kanji: '氏', meaning: 'mr. (speculum radical)' },
  { kanji: '底', meaning: 'bottom' },
  { kanji: '紙', meaning: 'paper' },
  { kanji: '低', meaning: 'low' },
  { kanji: '婚', meaning: 'marriage' },
  { kanji: '抵', meaning: 'resist' },
  { kanji: '民', meaning: 'folk' },
  { kanji: '眠', meaning: 'sleepy' },
  { kanji: '曲', meaning: 'song / turn or bend' },
  { kanji: '豊', meaning: 'plentiful' },
  { kanji: '典', meaning: 'classic' },
  { kanji: '遭', meaning: 'chance meeting、 usually with something bad' },
  { kanji: '農', meaning: 'farming' },
  { kanji: '濃', meaning: 'thick / dense' },
  { kanji: '辱', meaning: 'humiliate' },
  { kanji: '娠', meaning: 'pregnancy' },
  { kanji: '振', meaning: 'brandish / pretend' },
  { kanji: '唇', meaning: 'lips' },
  { kanji: '登', meaning: 'climb' },
  { kanji: '祭', meaning: 'festival' },
  { kanji: '際', meaning: 'edge' },
  { kanji: '察', meaning: 'police' },
  { kanji: '擦', meaning: 'chafe' },
  { kanji: '開', meaning: 'open' },
  { kanji: '発', meaning: 'launch' },
  { kanji: '廃', meaning: 'wane' },
  { kanji: '形', meaning: 'form' },
  { kanji: '研', meaning: 'polish, sharpen' },
  { kanji: '刑', meaning: 'penalty' },
  { kanji: '型', meaning: 'type / proper way' },
  { kanji: '午', meaning: 'noon' },
  { kanji: '許', meaning: 'allow' },
  { kanji: '牛', meaning: 'cow' },
  { kanji: '件', meaning: 'incident' },
  { kanji: '特', meaning: 'special' },
  { kanji: '牲', meaning: 'sacrificial victim' },
  { kanji: '犠', meaning: 'sacrifice' },
  { kanji: '解', meaning: 'solve / untie' },
  { kanji: '物', meaning: 'animal / thing' },
  { kanji: '惚', meaning: 'to fall in love with' },
  { kanji: '易', meaning: 'easy' },
  { kanji: '湯', meaning: 'hot water' },
  { kanji: '揚', meaning: 'hoist / deep fat fry' },
  { kanji: '陽', meaning: 'sun' },
  { kanji: '傷', meaning: 'wound' },
  { kanji: '場', meaning: 'place' },
  { kanji: '色', meaning: 'color' },
  { kanji: '免', meaning: 'exemption / license' },
  { kanji: '逸', meaning: 'more or less than normal' },
  { kanji: '晩', meaning: 'night' },
  { kanji: '絶', meaning: 'extinct' },
  { kanji: '勉', meaning: 'try hard' },
  { kanji: '声', meaning: 'voice' },
  { kanji: '肥', meaning: 'obese / manure' },
  { kanji: '豚', meaning: 'pig' },
  { kanji: '象', meaning: 'elephant / phenomenon' },
  { kanji: '像', meaning: 'statue / image' },
  { kanji: '縁', meaning: 'rim / omen' },
  { kanji: '家', meaning: 'home' },
  { kanji: '嫁', meaning: 'bride' },
  { kanji: '稼', meaning: 'bring home the loot' },
  { kanji: '遂', meaning: 'attain' },
  { kanji: '隊', meaning: 'troop' },
  { kanji: '行', meaning: 'go' },
  { kanji: '徐', meaning: 'slowly' },
  { kanji: '徒', meaning: 'pupil / follower' },
  { kanji: '径', meaning: 'diameter' },
  { kanji: '後', meaning: 'afterwards / behind' },
  { kanji: '往', meaning: 'depart' },
  { kanji: '待', meaning: 'wait' },
  { kanji: '得', meaning: 'bargain　/ obtain' },
  { kanji: '従', meaning: 'obey' },
  { kanji: '縦', meaning: 'vertical' },
  { kanji: '術', meaning: 'art / technique' },
  { kanji: '衝', meaning: 'collision' },
  { kanji: '微', meaning: 'teeny' },
  { kanji: '徴', meaning: 'sign / indication' },
  { kanji: '育', meaning: 'grow up / be raised' },
  { kanji: '徹', meaning: 'do thoroughly' },
  { kanji: '撤', meaning: 'withdraw' },
  { kanji: '流', meaning: 'flow' },
  { kanji: '陰', meaning: 'shady' },
  { kanji: '充', meaning: 'fill up' },
  { kanji: '銃', meaning: 'gun' },
  { kanji: '統', meaning: 'tradition' },
  { kanji: '至', meaning: 'until' },
  { kanji: '到', meaning: 'arrive' },
  { kanji: '致', meaning: 'polite \\"do\\"' },
  { kanji: '倒', meaning: 'knock down' },
  { kanji: '去', meaning: 'past tense' },
  { kanji: '法', meaning: 'law' },
  { kanji: '怯', meaning: 'get afeared' },
  { kanji: '屋', meaning: 'store' },
  { kanji: '室', meaning: 'room suffix' },
  { kanji: '握', meaning: 'grasp' },
  { kanji: '貿', meaning: 'international trading' },
  { kanji: '留', meaning: 'absent / stopped' },
  { kanji: '云', meaning: 'twin decapited cows' },
  { kanji: '転', meaning: 'roll over' },
  { kanji: '伝', meaning: 'transmit' },
  { kanji: '魂', meaning: 'soul' },
  { kanji: '芸', meaning: 'art' },
  { kanji: '会', meaning: 'big meeting' },
  { kanji: '絵', meaning: 'picture' },
  { kanji: '街', meaning: 'shopping district' },
  { kanji: '掛', meaning: 'hang / halfway done' },
  { kanji: '涯', meaning: 'lifetime' },
  { kanji: '封', meaning: 'seal in' },
  { kanji: '陸', meaning: 'continent' },
  { kanji: '勢', meaning: 'power' },
  { kanji: '熱', meaning: 'hot thing / fever' },
  { kanji: '冗', meaning: 'joke' },
  { kanji: '肌', meaning: 'human skin' },
  { kanji: '抗', meaning: 'oppose' },
  { kanji: '机', meaning: 'desk' },
  { kanji: '風', meaning: 'wind / the flu / style' },
  { kanji: '飢', meaning: 'starve' },
  { kanji: '処', meaning: 'dispose of　or manage' },
  { kanji: '拠', meaning: 'evidence which is the basis for a judgment' },
  { kanji: '凡', meaning: 'mediocre' },
  { kanji: '築', meaning: 'architect' },
  { kanji: '恐', meaning: 'dread' },
  { kanji: '投', meaning: 'throw' },
  { kanji: '役', meaning: 'role' },
  { kanji: '設', meaning: 'establish' },
  { kanji: '没', meaning: 'downfall' },
  { kanji: '殺', meaning: 'kill' },
  { kanji: '殴', meaning: 'punch' },
  { kanji: '股', meaning: 'grrrrrroin' },
  { kanji: '撃', meaning: 'charge' },
  { kanji: '盾', meaning: 'shield' },
  { kanji: '循', meaning: 'circulate' },
  { kanji: '真', meaning: 'really' },
  { kanji: '慎', meaning: 'refrain / be prudent' },
  { kanji: '県', meaning: 'prefecture' },
  { kanji: '懸', meaning: 'suspend / gamble' },
  { kanji: '直', meaning: 'correct a problem / direct contact' },
  { kanji: '置', meaning: 'put down on table' },
  { kanji: '値', meaning: 'price or ranking' },
  { kanji: '植', meaning: 'plant' },
  { kanji: '殖', meaning: 'agricultural breeding, reproduction' },
  { kanji: '別', meaning: 'separate' },
  { kanji: '列', meaning: 'row' },
  { kanji: '裂', meaning: 'tear up' },
  { kanji: '烈', meaning: 'violently intense' },
  { kanji: '例', meaning: 'example' },
  { kanji: '支', meaning: 'support' },
  { kanji: '皮', meaning: 'skin' },
  { kanji: '彼', meaning: 'him' },
  { kanji: '枝', meaning: 'branch' },
  { kanji: '技', meaning: 'technique' },
  { kanji: '鼓', meaning: 'drum' },
  { kanji: '破', meaning: 'rend' },
  { kanji: '波', meaning: 'wave' },
  { kanji: 'マ', meaning: 'Mama' },
  { kanji: '勇', meaning: 'courage' },
  { kanji: '予', meaning: 'beforehand' },
  { kanji: '序', meaning: 'first part / preface' },
  { kanji: '預', meaning: 'deposit' },
  { kanji: '野', meaning: 'field' },
  { kanji: '矛', meaning: 'halberd' },
  { kanji: '柔', meaning: 'flexible' },
  { kanji: '務', meaning: 'perform a task' },
  { kanji: '束', meaning: 'bundle of sticks' },
  { kanji: '疎', meaning: 'shun' },
  { kanji: '頼', meaning: 'ask a favor' },
  { kanji: '速', meaning: 'fast' },
  { kanji: '整', meaning: 'arrange' },
  { kanji: '通', meaning: 'pass' },
  { kanji: '踊', meaning: 'dance' },
  { kanji: '丙', meaning: 't-bone steak' },
  { kanji: '柄', meaning: 'pattern' },
  { kanji: '病', meaning: 'sick kanji' },
  { kanji: '痛', meaning: 'hurts!!!' },
  { kanji: '疲', meaning: 'get tired from hard work' },
  { kanji: '痢', meaning: 'diarrhea' },
  { kanji: '痴', meaning: 'molester' },
  { kanji: '症', meaning: 'symptom' },
  { kanji: '痺', meaning: 'go numb' },
  { kanji: '癒', meaning: 'cure' },
  { kanji: '愉', meaning: 'pleasure' },
  { kanji: '諭', meaning: 'chide / guide' },
  { kanji: '輸', meaning: 'transport' },
  { kanji: '癖', meaning: 'bad habit' },
  { kanji: '避', meaning: 'avoid / dodge' },
  { kanji: '壁', meaning: 'wall' },
  { kanji: '療', meaning: 'medical therapy' },
  { kanji: '寮', meaning: 'dormitory' },
  { kanji: '僚', meaning: 'coworker' },
  { kanji: '申', meaning: 'humbly say (god radical)' },
  { kanji: '痩', meaning: 'lose weight' },
  { kanji: '紳', meaning: 'gentleman' },
  { kanji: '捜', meaning: 'search' },
  { kanji: '伸', meaning: 'stretch' },
  { kanji: '甲', meaning: 'turtle shell' },
  { kanji: '押', meaning: 'push' },
  { kanji: '由', meaning: 'freedom / reason' },
  { kanji: '抽', meaning: 'abstract' },
  { kanji: '宙', meaning: 'space' },
  { kanji: '油', meaning: 'oil' },
  { kanji: '届', meaning: 'extend to' },
  { kanji: '偶', meaning: 'coincidence' },
  { kanji: '隅', meaning: 'corner of room' },
  { kanji: '愚', meaning: 'dum diddy dum dum' },
  { kanji: '雨', meaning: 'rain' },
  { kanji: '霧', meaning: 'fog' },
  { kanji: '雲', meaning: 'cloud' },
  { kanji: '曇', meaning: 'get cloudy' },
  { kanji: '霜', meaning: 'frost' },
  { kanji: '雷', meaning: 'lightning' },
  { kanji: '震', meaning: 'shake, tremble' },
  { kanji: '漏', meaning: 'leak' },
  { kanji: '雪', meaning: 'snow' },
  { kanji: '雰', meaning: 'atmosphere' },
  { kanji: '露', meaning: 'outdoors, public' },
  { kanji: '霊', meaning: 'ghost' },
  { kanji: '湿', meaning: 'become damp, moisten' },
  { kanji: '業', meaning: 'business' },
  { kanji: '僕', meaning: 'me (for dudes)' },
  { kanji: '撲', meaning: 'eradicate' },
  { kanji: '竜', meaning: 'dragon' },
  { kanji: '滝', meaning: 'waterfall' },
  { kanji: '電', meaning: 'electricity' },
  { kanji: '俺', meaning: 'me (macho version)' },
  { kanji: '亀', meaning: 'turtle' },
  { kanji: '縄', meaning: 'rope' },
  { kanji: '需', meaning: 'demand' },
  { kanji: '耐', meaning: 'withstand' },
  { kanji: '端', meaning: 'the edge' },
  { kanji: '包', meaning: 'wrap' },
  { kanji: '胞', meaning: 'cell' },
  { kanji: '泡', meaning: 'bubble' },
  { kanji: '砲', meaning: 'cannon' },
  { kanji: '飽', meaning: 'get sick of' },
  { kanji: '抱', meaning: 'hug' },
  { kanji: '胸', meaning: 'chest/breast' },
  { kanji: '句', meaning: 'verse of a poem' },
  { kanji: '敬', meaning: 'respect' },
  { kanji: '警', meaning: 'the fuzz' },
  { kanji: '驚', meaning: 'astonish' },
  { kanji: '局', meaning: 'department' },
  { kanji: '拘', meaning: 'put in custody' },
  { kanji: '旬', meaning: 'in season/ time of month' },
  { kanji: '陶', meaning: 'pottery' },
  { kanji: '匂', meaning: 'scent (good or bad)' },
  { kanji: '渇', meaning: 'thirsty' },
  { kanji: '約', meaning: 'promise/ roughly speaking' },
  { kanji: '的', meaning: 'motivation / \\'-al\\'' },
  { kanji: '釣', meaning: 'fishin' },
  { kanji: '均', meaning: 'average' },
  { kanji: '皿', meaning: 'plate' },
  { kanji: '盗', meaning: 'steal by stealth' },
  { kanji: '温', meaning: 'hot or warm thing' },
  { kanji: '盟', meaning: 'oath' },
  { kanji: '盛', meaning: 'heaps of!' },
  { kanji: '塩', meaning: 'salt' },
  { kanji: '監', meaning: 'oversee' },
  { kanji: '鑑', meaning: 'expert opinion' },
  { kanji: '血', meaning: 'blood' },
  { kanji: '衆', meaning: 'populace' },
  { kanji: '益', meaning: 'profit' },
  { kanji: '溢', meaning: 'overflow' },
  { kanji: '誉', meaning: 'honor' },
  { kanji: '挙', meaning: 'raise / cite/ mention' },
  { kanji: '舟', meaning: 'boat' },
  { kanji: '船', meaning: 'ship' },
  { kanji: '航', meaning: 'navigation' },
  { kanji: '般', meaning: 'general / overall' },
  { kanji: '盤', meaning: 'tray / basis' },
  { kanji: '猫', meaning: 'cat' },
  { kanji: '猛', meaning: 'fierce' },
  { kanji: '猥', meaning: 'obscene' },
  { kanji: '猿', meaning: 'monkey' },
  { kanji: '狩', meaning: 'hunt' },
  { kanji: '狂', meaning: 'go nuts' },
  { kanji: '独', meaning: 'solitary' },
  { kanji: '獄', meaning: 'hell' },
  { kanji: '獲', meaning: 'prey on　/ get' },
  { kanji: '狭', meaning: 'narrow' },
  { kanji: '犯', meaning: 'commit a crime' },
  { kanji: '印', meaning: 'stamp' },
  { kanji: '叩', meaning: 'beat, smack' },
  { kanji: '卵', meaning: 'egg' },
  { kanji: '却', meaning: 'disregard' },
  { kanji: '範', meaning: 'standard / the best way to do' },
  { kanji: '御', meaning: 'the honorific \\"o\\"' },
  { kanji: '腕', meaning: 'arm / skill' },
  { kanji: '即', meaning: 'immediately' },
  { kanji: '節', meaning: 'season / joint' },
  { kanji: '厄', meaning: 'misfortune' },
  { kanji: '危', meaning: 'dangerous' },
  { kanji: '抑', meaning: 'suppress' },
  { kanji: '迎', meaning: 'go to pick someone up' },
  { kanji: '仰', meaning: 'pompous / look up to' },
  { kanji: '服', meaning: 'clothes' },
  { kanji: '報', meaning: 'data' },
  { kanji: '狙', meaning: 'aim at' },
  { kanji: '組', meaning: 'one\\'s team' },
  { kanji: '阻', meaning: 'hamper' },
  { kanji: '粗', meaning: 'rough texture / bad quality' },
  { kanji: '査', meaning: 'inspect' },
  { kanji: '畳', meaning: 'tatami mat' },
  { kanji: '助', meaning: 'save' },
  { kanji: 'ネ', meaning: 'NEcrophilia' },
  { kanji: '祖', meaning: 'ancestor' },
  { kanji: '視', meaning: 'peer at' },
  { kanji: '祝', meaning: 'celebrate' },
  { kanji: '社', meaning: 'company' },
  { kanji: '祈', meaning: 'pray' },
  { kanji: '祉', meaning: 'welfare' },
  { kanji: '神', meaning: 'GOD kanji' },
  { kanji: '福', meaning: 'good luck' },
  { kanji: '副', meaning: 'side- or vice-' },
  { kanji: '幅', meaning: 'width' },
  { kanji: '富', meaning: 'get rich' },
  { kanji: '礼', meaning: 'polite' },
  { kanji: '乱', meaning: 'disorder' },
  { kanji: '札', meaning: 'card / label / bill' },
  { kanji: '乳', meaning: 'milk' },
  { kanji: '初', meaning: 'first time' },
  { kanji: '裸', meaning: 'naked' },
  { kanji: '被', meaning: 'get injured' },
  { kanji: '複', meaning: 'complicated or compound' },
  { kanji: '腹', meaning: 'entrails' },
  { kanji: '復', meaning: 'return or re-do' },
  { kanji: '履', meaning: 'put on pants or shoes' },
  { kanji: '谷', meaning: 'valley (Swamp Thing radical)' },
  { kanji: '裕', meaning: 'abundant' },
  { kanji: '欲', meaning: 'want' },
  { kanji: '俗', meaning: 'uncouth' },
  { kanji: '容', meaning: 'appearance' },
  { kanji: '溶', meaning: 'melt' },
  { kanji: '浴', meaning: 'bathe' },
  { kanji: '鼻', meaning: 'nose' },
  { kanji: '葬', meaning: 'mourn' },
  { kanji: '算', meaning: 'calculate' },
  { kanji: '弁', meaning: 'dialect' },
  { kanji: '昇', meaning: 'ascend' },
  { kanji: '戒', meaning: 'admonish / commandment' },
  { kanji: '械', meaning: 'contraption' },
  { kanji: '羽', meaning: 'feathers' },
  { kanji: '飛', meaning: 'fly' },
  { kanji: '翌', meaning: 'the next- / the following -' },
  { kanji: '習', meaning: 'learn' },
  { kanji: '弱', meaning: 'weak' },
  { kanji: '扇', meaning: 'traditional fan' },
  { kanji: '散', meaning: 'scatter' },
  { kanji: '展', meaning: 'exhibit' },
  { kanji: '譲', meaning: 'concessions' },
  { kanji: '昔', meaning: 'long ago' },
  { kanji: '借', meaning: 'borrow' },
  { kanji: '惜', meaning: 'close but no cigar' },
  { kanji: '籍', meaning: 'family register' },
  { kanji: '黄', meaning: 'yellow' },
  { kanji: '嬢', meaning: 'young lady' },
  { kanji: '横', meaning: 'side / arrogant' },
  { kanji: '共', meaning: 'with' },
  { kanji: '並', meaning: 'line up / ordinary' },
  { kanji: '普', meaning: 'normal' },
  { kanji: '供', meaning: 'follower' },
  { kanji: '選', meaning: 'choose' },
  { kanji: '洪', meaning: 'flood' },
  { kanji: '巷', meaning: 'Tha $treetz' },
  { kanji: '港', meaning: 'harbor' },
  { kanji: '異', meaning: 'to differ' },
  { kanji: '翼', meaning: 'political wing' },
  { kanji: '暴', meaning: 'rampage' },
  { kanji: '爆', meaning: 'explode' },
  { kanji: '再', meaning: 'again / once more' },
  { kanji: '甫', meaning: 'unicycle' },
  { kanji: '舗', meaning: 'chain store' },
  { kanji: '補', meaning: 'supplement' },
  { kanji: '捕', meaning: 'capture' },
  { kanji: '構', meaning: 'set up / care about' },
  { kanji: '講', meaning: 'lecture' },
  { kanji: '購', meaning: 'subscribe' },
  { kanji: '溝', meaning: 'ditch' },
  { kanji: '降', meaning: 'descend /rainfall / get out of vehicle' },
  { kanji: '年', meaning: 'year' },
  { kanji: '五', meaning: 'five' },
  { kanji: '語', meaning: 'language' },
  { kanji: '悟', meaning: 'enlightenment' },
  { kanji: '違', meaning: 'different and therefore wrong' },
  { kanji: '偉', meaning: 'high-powered, prestigious' },
  { kanji: '衛', meaning: 'defense' },
  { kanji: '瞬', meaning: 'twinkle / tiny bit of time' },
  { kanji: '舞', meaning: 'dance / flutter' },
  { kanji: '隣', meaning: 'neighbor' },
  { kanji: '料', meaning: 'ingredients / fees' },
  { kanji: '科', meaning: 'science' },
  { kanji: '図', meaning: 'diagram/ map' },
  { kanji: '斜', meaning: 'diagonal' },
  { kanji: '史', meaning: 'history' },
  { kanji: '更', meaning: 'all over again' },
  { kanji: '硬', meaning: 'hard like a rock' },
  { kanji: '使', meaning: 'use' },
  { kanji: '便', meaning: 'convenient　/ poop' },
  { kanji: '身', meaning: '(one\\'s own) flesh' },
  { kanji: '射', meaning: 'shoot' },
  { kanji: '謝', meaning: 'apologize' },
  { kanji: '窮', meaning: 'to be in trouble' },
  { kanji: '地', meaning: 'area' },
  { kanji: '池', meaning: 'pond' },
  { kanji: '他', meaning: 'other' },
  { kanji: '施', meaning: 'put into practice / charity' },
  { kanji: '曽', meaning: 'gain' },
  { kanji: '増', meaning: 'increase' },
  { kanji: '贈', meaning: 'give' },
  { kanji: '憎', meaning: 'detest' },
  { kanji: '僧', meaning: 'buddhist monk' },
  { kanji: '層', meaning: 'layer' },
  { kanji: '呂', meaning: 'washtub' },
  { kanji: '宮', meaning: 'palace' },
  { kanji: '官', meaning: 'federal' },
  { kanji: '館', meaning: 'big hall' },
  { kanji: '棺', meaning: 'coffin' },
  { kanji: '追', meaning: 'follow' },
  { kanji: '遣', meaning: 'apply' },
  { kanji: '管', meaning: 'tube' },
  { kanji: '師', meaning: 'master, teacher' },
  { kanji: '営', meaning: 'manage (a business)' },
  { kanji: '労', meaning: 'labor' },
  { kanji: '栄', meaning: 'glory' },
  { kanji: '学', meaning: 'knowledge' },
  { kanji: '覚', meaning: 'bear in mind' },
  { kanji: '党', meaning: 'political party' },
  { kanji: '尚', meaning: 'all the more' },
  { kanji: '賞', meaning: 'prize' },
  { kanji: '償', meaning: 'compensate for' },
  { kanji: '常', meaning: 'usual' },
  { kanji: '堂', meaning: 'assembly hall' },
  { kanji: '善', meaning: 'morally good' },
  { kanji: '繕', meaning: 'mend' },
  { kanji: '周', meaning: 'circumference' },
  { kanji: '調', meaning: 'check out' },
  { kanji: '週', meaning: 'week' },
  { kanji: '彫', meaning: 'carve' },
  { kanji: '高', meaning: 'tall' },
  { kanji: '豪', meaning: 'luxurious' },
  { kanji: '向', meaning: 'turn to face' },
  { kanji: '商', meaning: 'merchandise' },
  { kanji: '橋', meaning: 'bridge' },
  { kanji: '過', meaning: 'surpass / too much' },
  { kanji: '骨', meaning: 'bone' },
  { kanji: '滑', meaning: 'slippery' },
  { kanji: '率', meaning: 'ratio' },
  { kanji: '渋', meaning: 'bitter flavor' },
  { kanji: '楽', meaning: 'enjoy' },
  { kanji: '薬', meaning: 'medicine' },
  { kanji: '兆', meaning: 'omen' },
  { kanji: '逃', meaning: 'escape' },
  { kanji: '跳', meaning: 'leap up' },
  { kanji: '眺', meaning: 'look at for a long time while lost in thought' },
  { kanji: '挑', meaning: 'challenge' },
  { kanji: '桃', meaning: 'peach' },
  { kanji: '書', meaning: 'write' },
  { kanji: '律', meaning: 'regulation' },
  { kanji: '事', meaning: 'action/ incident' },
  { kanji: '筆', meaning: 'paintbrush' },
  { kanji: '唐', meaning: 'suddenly' },
  { kanji: '糖', meaning: 'sugar' },
  { kanji: '逮', meaning: 'arrest' },
  { kanji: '康', meaning: 'health' },
  { kanji: '棄', meaning: 'discard' },
  { kanji: '君', meaning: 'buddy' },
  { kanji: '群', meaning: 'flock' },
  { kanji: '妻', meaning: 'wife' },
  { kanji: '凄', meaning: 'deeyammn / hella' },
  { kanji: '争', meaning: 'battle' },
  { kanji: '静', meaning: 'quiet' },
  { kanji: '兼', meaning: 'double-duty' },
  { kanji: '嫌', meaning: 'eww!!' },
  { kanji: '謙', meaning: 'modesty' },
  { kanji: '建', meaning: 'build' },
  { kanji: '健', meaning: 'healthy' },
  { kanji: '延', meaning: 'prolong' },
  { kanji: '誕', meaning: 'birthday / birth' },
  { kanji: '庭', meaning: 'garden' },
  { kanji: '銭', meaning: 'coin' },
  { kanji: '浅', meaning: 'shallow' },
  { kanji: '残', meaning: 'remain behind' },
  { kanji: '聴', meaning: 'listen to' },
  { kanji: '壊', meaning: 'break' },
  { kanji: '懐', meaning: 'nostalgia' },
  { kanji: '徳', meaning: 'virtue' },
  { kanji: '劇', meaning: 'play' },
  { kanji: '慮', meaning: 'consideration' },
  { kanji: '虚', meaning: 'empty' },
  { kanji: '虐', meaning: 'oppress' },
  { kanji: '膚', meaning: 'epidermis' },
  { kanji: '嘘', meaning: 'lie' },
  { kanji: '沈', meaning: 'sink' },
  { kanji: '就', meaning: 'get a job, you bum!' },
  { kanji: '蹴', meaning: 'kick' },
  { kanji: '刻', meaning: 'engrave' },
  { kanji: '核', meaning: 'nucleus' },
  { kanji: '該', meaning: 'correspond to' },
  { kanji: '咳', meaning: 'cough' },
  { kanji: '之', meaning: 'this' },
  { kanji: '乏', meaning: 'shoddy' },
  { kanji: '芝', meaning: 'lawn' },
  { kanji: '其', meaning: 'that' },
  { kanji: '旗', meaning: 'flag' },
  { kanji: '基', meaning: 'basis' },
  { kanji: '期', meaning: 'period of time' },
  { kanji: '欺', meaning: 'dupe' },
  { kanji: '甚', meaning: 'enormous' },
  { kanji: '勘', meaning: 'perception' },
  { kanji: '堪', meaning: 'tolerate' },
  { kanji: '邪', meaning: 'heresy' },
  { kanji: '既', meaning: 'already' },
  { kanji: '雅', meaning: 'elegant' },
  { kanji: '概', meaning: 'general concept' },
  { kanji: '慨', meaning: 'deplore' },
  { kanji: '屯', meaning: 'bent dagger' },
  { kanji: '純', meaning: 'epitome' },
  { kanji: '鈍', meaning: 'dull' },
  { kanji: '逆', meaning: 'opposite' },
  { kanji: '以', meaning: 'compared to' },
  { kanji: '似', meaning: 'resemble' },
  { kanji: '承', meaning: 'to be told　/ consent' },
  { kanji: '蒸', meaning: 'humid' },
  { kanji: '段', meaning: 'step / stairs' },
  { kanji: '興', meaning: 'interest' },
  { kanji: '暇', meaning: 'free time' },
  { kanji: '龍', meaning: 'ancient Chinese dragon' },
  { kanji: '襲', meaning: 'onslaught' },
  { kanji: '巡', meaning: 'patrol' },
  { kanji: '災', meaning: 'disaster' },
  { kanji: '呉', meaning: 'Wu dynasty of China' },
  { kanji: '誤', meaning: 'mistake' },
  { kanji: '娯', meaning: 'entertainment' },
  { kanji: '瓜', meaning: 'melon' },
  { kanji: '孤', meaning: 'isolation' },
  { kanji: '弧', meaning: 'arc' },
  { kanji: '為', meaning: 'deed' },
  { kanji: '偽', meaning: 'fake' },
  { kanji: '融', meaning: 'fusion' },
  { kanji: '隔', meaning: 'segregate' },
  { kanji: '丈', meaning: 'robust' },
  { kanji: '拝', meaning: 'worship' },
  { kanji: '互', meaning: 'reciprocal' },
  { kanji: '麗', meaning: 'gorgeous' }
];

// Export for Node.js
if (typeof module !== 'undefined' && module.exports) {
  module.exports = kanjiData;
}
